// This is original code generated by create-react-native-library:

// const path = require('path');
// const { getConfig } = require('react-native-builder-bob/babel-config');
// const pkg = require('../package.json');

// const root = path.resolve(__dirname, '..');

// module.exports = getConfig(
//   {
//     presets: ['module:@react-native/babel-preset'],
//   },
//   { root, pkg }
// );

// This is workaround to support classes:

const path = require('path');
const pak = require('../package.json');

module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        alias: {
          [pak.name]: path.join(__dirname, '..', pak.source),
        },
      },
    ],
  ],
};
